export const GET_TAX_CLEARANCES_REQUEST="GET_TAX_CLEARANCES_REQUEST";
export const GET_TAX_CLEARANCES_SUCCESS="GET_TAX_CLEARANCES_SUCCESS";
export const GET_TAX_CLEARANCES_FAIL="GET_TAX_CLEARANCES_FAIL";


export const GET_TAX_CLEARANCE_REQUEST="GET_TAX_CLEARANCE_REQUEST";
export const GET_TAX_CLEARANCE_SUCCESS="GET_TAX_CLEARANCE_SUCCESS";
export const GET_TAX_CLEARANCE_FAIL="GET_TAX_CLEARANCE_FAIL";

export const CREATE_TAX_CLEARANCE_REQUEST="CREATE_TAX_CLEARANCE_REQUEST";
export const CREATE_TAX_CLEARANCE_SUCCESS="CREATE_TAX_CLEARANCE_SUCCESS";
export const CREATE_TAX_CLEARANCE_FAIL="CREATE_TAX_CLEARANCE_FAIL";







export const UPDATE_TAX_CLEARANCE_REQUEST="UPDATE_TAX_CLEARANCE_REQUEST";
export const UPDATE_TAX_CLEARANCE_SUCCESS="UPDATE_TAX_CLEARANCE_SUCCESS";
export const UPDATE_TAX_CLEARANCE_FAIL="UPDATE_TAX_CLEARANCE_FAIL";


export const DELETE_TAX_CLEARANCE_REQUEST="DELETE_TAX_CLEARANCE_REQUEST";
export const DELETE_TAX_CLEARANCE_SUCCESS="DELETE_TAX_CLEARANCE_SUCCESS";
export const DELETE_TAX_CLEARANCE_FAIL="DELETE_TAX_CLEARANCE_FAIL";

